### PR TITLE
Integration of new angular-ionic version and correction of ion-navbar overlap

### PR DESCRIPTION
**Pull request by oliviercherrier**
1. Commit 38d55ee is to manage new ionic-angular version dependencies.
2. Commit ead454d is to fix the following bug:

    Expected behavior: since logged in, be redirected to the ion-tabs and display the current ion-tab that include a ion-navbar as in ScreenShot "Expected behavior"
    Old behavior: ion-navbar overlap the top of ion-content of ion-tab (as in  screenshot "Old Behavior".
   Description: I put a navController.push(TabsPage) in the callback of authentificated to force the redraw of the tabsPage. And I need to put a timeOut to wait for div will be put into DOM. What do you think about this solution. Better one will be very welcome!!!

Thank you for your help.

Oliv.

Old Behavior:
old behavior

Expected (patched) behavior:
expected behavior

### CODE REVIEW

**Comment by oliviercherrier** [comment]
Can you give me feedback on this pull request ?

Thank you

**Comment by chenkie** [comment]
Hey @oliviercherrier, sorry for the delay on this. Thanks for your PR :)

We're actually just in the process of updating this to ionic-angular RC0, but it would be good to have a beta update in the interim.

I tried running with the deps you provided but I get this: 

`Cannot find module '@angular/forms' from '/Users/ryanchenkie/Desktop/code/auth0-ionic2.test/node_modules/ionic-angular/config'`

Can you check the deps?

Thanks!

**Comment by oliviercherrier** [comment]
Hello @chenkie 

Thank you for your answer!

I commit the new version with the @angular/forms dependendy.

**Comment by chenkie** [comment]
Shouldn't the forms dep be `2.0.0-rc.4`?

**Comment by oliviercherrier** [comment]
Hi @chenkie 

the version 2.0.0-rc4 of forms does not exist. I tried with the last version, without succcess: 

```
npm ERR! peerinvalid The package @angular/common@2.0.0-rc.4 does not satisfy its
 siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/forms@2.0.2 wants @angular/common@2.0.2
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.4 wants @angular/co
mmon@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.4 wants @an
gular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer ionic-angular@2.0.0-beta.11 wants @angular/common@2.0.
0-rc.4
```

I don't have a lot of time to optimize the version dependencies... Let me know if you need it to integrate the pull request.

**Comment by oliviercherrier** [comment]
Hi @chenkie 

do you need some complementary works from me ton  incorporate this pull request ?

**Comment by chenkie** [comment]
Looking good, thanks for your PR :)

**Comment by oliviercherrier** [comment]
Thank you.

**Pull request merged**
